### ISSUE TITLE
Issue using with Webpack

### ISSUE THREAD

**Issue by michaelryancaputo** [quickleft/react-loader#16] opened 2015-03-08 15:14 UTC
Hey there,
I seem to be getting an issue related to webpack and React-loader.

    ReferenceError: document is not defined
        at createEl (/Users/mike/Projects/bitwatcher/dist/server.js:94672:15)
        at /Users/mike/Projects/bitwatcher/dist/server.js:94693:15
        at /Users/mike/Projects/bitwatcher/dist/server.js:94696:5
        at prefixes (/Users/mike/Projects/bitwatcher/dist/server.js:94652:32)
        at Object.<anonymous> (/Users/mike/Projects/bitwatcher/dist/server.js:94660:2)
        at __webpack_require__ (/Users/mike/Projects/bitwatcher/dist/server.js:20:30)
        at React.createClass.displayName (/Users/mike/Projects/bitwatcher/dist/server.js:94535:64)
        at Object.<anonymous> (/Users/mike/Projects/bitwatcher/dist/server.js:94542:3)
        at __webpack_require__ (/Users/mike/Projects/bitwatcher/dist/server.js:20:30)
        at Object.<anonymous> (/Users/mike/Projects/bitwatcher/dist/server.js:5242:31)
    Program node dist/server exited with code 1

**Comment by mhuggins** [comment] 2015-03-08 15:23
I'm not familiar with Webpack.  What does your code look like, and what command are you running to see that error?

**Comment by michaelryancaputo** [comment] 2015-03-08 15:47
It seems like just loading the package into a component causes this issue.
I suggest giving this package a try with it: https://github.com/RickWong/react-isomorphic-starterkit

**Comment by dozoisch** [comment] 2015-03-26 15:29
:+1: Getting the same error trying to do some server side rendering.

**Comment by mhuggins** [comment] 2015-03-26 16:06
@dozoisch Curious about why you're trying to render a spinner on the server.  I haven't looked into this, but I'm wondering if it's to do with spin.js expecting to bind to the document in some sense.  It could be the way that I've implemented React itself though, since I haven't done anything server-side with it yet.

**Comment by mhuggins** [comment] 2015-03-26 16:09
Taking a quick look at the [spin.js](https://github.com/fgnass/spin.js/blob/master/spin.js) code and comparing that to what's in this, I'm creating a `new Spinner`, then calling `.spin` on it.  That ultimately calls `document.createElement` in spin.js, which would throw an error if there is no document.  Perhaps it would make sense to only create the spinner object if `document` exists.  (Not sure about Webpack since I've never used it and if the issue is the same there.)

**Comment by dozoisch** [comment] 2015-03-26 16:13
Yeah I'm trying to see why it gets called. From what I see it's just that it gets packaged by webpack on the server prerender script.

**Comment by mhuggins** [comment] 2015-03-30 22:20
Would it be difficult to throw together an extremely simple project that demonstrates the error?  Simply with however the server-side setup or Webpack is implementing react-loader?

**Comment by dozoisch** [comment] 2015-03-31 12:49
I'll try to set one up! I'm a bit in the rush right now but at least there is a workaround

**Comment by mhuggins** [comment] 2015-04-01 15:10
No worries, totally understandable.  I just haven't done a server-side setup with React yet, and it I wouldn't know if what I'm doing properly matches what is causing the error for you guys. :smile:

**Comment by mikekauffman** [comment] 2016-04-12 20:18
This should be fixed in v2.4.0. Please open a new issue if not.

**Closed by mikekauffman** 2016-04-12 20:18 UTC
